mysite/blog/urls.py
from django.urls import include, path

from blog import views
from blog.views import PostUpdateView

app_name = "blog"
post_urls = [
     path('create', views.PostCreateView.as_view(), name='create_post'),
     path('<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
     path('<int:pk>/delete', views.PostDeleteView.as_view(), name='post_delete'),
     path('<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),

]

urlpatterns = [
    path('home/', views.HomePageView.as_view(), name='home'),
    path('search', views.PostSearchView.as_view(), name='search_results'),
    path('posts/', include(post_urls)),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from blog import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

mysite/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    updated_at = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag, blank=True, related_name='posts')
    
    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

mysite/blog/forms.py
from django import forms
from blog.models import Post
from blog.models import Tag


class PostForm(forms.ModelForm):
    tags = forms.CharField(required=True)

    class Meta:
        model = Post
        fields = ['title', 'content']

    def save(self, commit=True):
        post = super().save(commit=False)
        tags = self.cleaned_data['tags'].split(',')
        tag_objects = [Tag.objects.get_or_create(name=tag_name.strip())[0] for tag_name in tags]
        post.save()
        post.tags.set(tag_objects)
        if commit:
            post.save()
        return post

mysite/blog/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import DeleteView, UpdateView

from blog.forms import PostForm
from blog.models import Post


class CustomLoginRequiredMixin(LoginRequiredMixin):
    login_url = reverse_lazy('login') 
    redirect_field_name = 'redirect_to'

class CustomPermissionRequiredMixin(PermissionRequiredMixin):
        
    def has_permission(self):
        post = self.get_object()
        return post.author == self.request.user
    
    def handle_no_permission(self):
        return HttpResponseForbidden()


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


class HomePageView(ListView):
    template_name = 'home.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        return Post.objects.order_by('-created_at')


class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'
    context_object_name = 'post'


class PostUpdateView(LoginRequiredMixin, CustomPermissionRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'post_update.html'

    def get_initial(self):
        initial = super().get_initial()
        post = self.get_object()
        initial['tags'] = ', '.join([tag.name for tag in post.tags.all()])
        return initial
    
    def get_success_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'pk': self.object.pk})


class PostCreateView(CustomLoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:home')
    template_name = 'create_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, CustomPermissionRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:home')
    permission_required = 'blog.delete_post'

    def get_object(self, queryset=None):
        obj = get_object_or_404(Post, pk=self.kwargs['pk'])
        return obj

class PostSearchView(ListView):
    model = Post
    template_name = 'search_results.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        searched = self.request.GET.get('searched')
        object_list = Post.objects.filter(
            Q(title__icontains=searched) | 
            Q(author__username__icontains=searched) |
            Q(tags__name__icontains=searched)
        ).distinct()
        
        return object_list
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('searched', '')
        return context

mysite/templates/base.html
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>

<body>
    <header>
        <div
            style="display: flex; flex-direction: row; justify-content: flex-end; align-items: center; background-color: lightgray; height: 5%;">
            {% block header %}
            {% include 'header.html' %}
            {% endblock %}
        </div>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>

</html>

mysite/templates/create_post.html
{% extends 'base.html' %}

{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block content %}

<h1>Create Post</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="author" value="{{ request.user.id }}">
    <div>
        <label>Tags</label>
        <input type="text" 
               name="tag_names">
      </div>
    <button type="submit">Create</button>
</form>

{% endblock content %}

mysite/templates/header.html
<div style="display: flex; flex-direction: row; justify-content: space-between;  align-items: center; margin-right: 50px; margin-left: 10px;">
        
        <form method="get" action="{% url 'blog:search_results' %}">
                {% csrf_token %}
                <input type="search" placeholder="Search" name="searched">
                <button type="submit">Search</button>
            </form>
        <p><a href="{% url 'blog:home' %}" style="margin-right: 10px;">Home</a></p>
    {% if user.is_authenticated %}
            <p><a href="{% url 'logout' %}" style="margin-right: 10px;">Log Out</a></p>
            <a href="{% url 'blog:create_post' %}"><button>Create new Post</button></a>
    
    
    {% else %}
            <a href="{% url 'login' %}" style="margin-right: 5px;">Log In</a>
            <a href="{% url 'signup' %}">Sign Up</a>
        
    {% endif %}
</div>

mysite/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<div style="display: flex; flex-direction: row; justify-content: flex-start; margin-right: 50px; margin-left: 10px;">
    <h1>Hi {{ user.username }}!</h1>
</div>

{% else %}
<div style="display: flex; flex-direction: row; justify-content: flex-start; margin-right: 50px; margin-left: 10px;">
    <h1>You are not logged in</h1>
</div>

{% endif %}
<div style="display: flex; flex-direction: column;">
    {% for post in post_list %}
    <a style="margin-left: 20px; margin-bottom: 20px;" href="{% url 'blog:post_detail' post.id  %}">{{post.title}} </a>

    {% endfor %}

</div>

{% endblock %}

mysite/templates/post_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ post.title }} </h1>
<p>{{ post.author }} | {{ post.created_on }}</p>
<div style="display: flex; flex-direction: row; justify-content: flex-start; align-items: center;">
  <h2 style="margin-right: 10px;">Tags:</h2>
  {% for tag in post.tags.all %}
  <p style="margin-right: 10px;">{{tag}} </p>

  {% endfor %}

</div>
<p>{{ post.content }}</p>
{% if user.is_authenticated and post.author == user %}
<form method="get" action="{% url 'blog:post_update' post.pk %}">
  {% csrf_token %}
  <label id="post_content_text" name="post_content_text">{{ post.content }}</label>
  <button type="submit">Edit Blog</button>
</form>
<form method="post" action="{% url 'blog:post_delete' post.pk %}">
  {% csrf_token %}
  <input type="submit" value="Delete">
</form>

{% endif %}

{% endblock content %}

mysite/templates/post_update.html
{% extends 'base.html' %}

{% block content %}

<h1>Edit Post</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="author" value="{{ request.user.id }}">
    <button type="submit">Save</button>
</form>

{% endblock content %}

mysite/templates/search_results.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<div style="display: flex; flex-direction: row; justify-content: flex-start; margin-right: 50px; margin-left: 10px;">
    <h1>Hi {{ user.username }}!</h1>
</div>

{% else %}
<div style="display: flex; flex-direction: row; justify-content: flex-start; margin-right: 50px; margin-left: 10px;">
    <h1>You are not logged in</h1>
</div>

{% endif %}

{% if search and posts %}
<p>Search results for: "{{ search }}"</p>
<ul>
    {% for post in posts %}
    <li>
        <a style="margin-left: 20px; margin-bottom: 20px;"
            href="{% url 'blog:post_detail' post.id  %}">{{post.title}}</a>
        by {{ post.author }}
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No results found for <strong>{{ search }}</strong>.</p>
{% endif %}

{% endblock %}